name: Build APK
on: push
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libffi-dev python3-dev \
          libssl-dev cmake git zip unzip openjdk-17-jdk python3-pip \
          autoconf libtool pkg-config zlib1g-dev libncurses5-dev \
          libncursesw5-dev libgdbm-dev libsqlite3-dev libdb5.3-dev \
          libbz2-dev libexpat1-dev liblzma-dev tk-dev lld
          pip install --upgrade pip
          pip install "cython<3.0" buildozer

      - name: Build APK with Buildozer
        run: |
          # 1. Приймаємо ліцензії в системному SDK
          yes | sdkmanager --licenses || true
          
          # 2. Запускаємо збірку, вказуючи шлях до системного SDK прямо в команді
          # Це змусить Buildozer не качати свій SDK, а взяти готовий
          buildozer -v android debug
        env:
          # Вказуємо правильні шляхи до встановлених на GitHub інструментів
          ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
          ANDROID_NDK_ROOT: /usr/local/lib/android/sdk/ndk/25.2.9519653
