name: Build APK
on: push
jobs:
  build:
    runs-on: ubuntu-22.04  # Фіксуємо стабільну версію системи
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libffi-dev python3-dev \
          libssl-dev cmake git zip unzip openjdk-17-jdk python3-pip \
          autoconf libtool pkg-config zlib1g-dev libncurses5-dev \
          libncursesw5-dev libgdbm-dev libsqlite3-dev libdb5.3-dev \
          libbz2-dev libexpat1-dev liblzma-dev tk-dev lld
          pip install --upgrade pip
          pip install "cython<3.0" buildozer  # Фіксуємо версію Cython

      - name: Build APK with Buildozer
        run: |
          # Видаляємо старі спроби, щоб почати "з чистого листа"
          rm -rf .buildozer
          # Запускаємо збірку з детальним логом
          buildozer -v android debug
        env:
          # Це змусить Buildozer не питати дозволів, а просто працювати
          APP_ALLOW_BACKUP: 1
